M48
; DRILL file KiCad 10.0.1 date 2026-05-04T15:27:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-04T15:27:02+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X77.49Y-89.0
X77.49Y-135.95
X102.0Y-89.0
X102.0Y-135.95
T2
X75.0Y-77.5
X75.0Y-159.5
X167.0Y-77.5
X167.0Y-159.5
M30
